const fs = require('fs');
const path = require('path');

const CODE_EXTS = new Set(['.js', '.jsx', '.ts', '.tsx', '.py', '.java', '.go', '.rs', '.rb', '.php', '.cs', '.cpp', '.c', '.h', '.mjs', '.cjs']);
const DOC_EXTS = new Set(['.md', '.txt', '.json', '.yml', '.yaml']);
const IGNORE_DIRS = new Set(['.git', 'node_modules', '.next', 'dist', 'build', 'coverage', 'graphify-out', '__pycache__', '.venv', 'venv']);

function safeRelative(root, filePath) {
  return path.relative(root, filePath).replace(/\\/g, '/');
}

function walkFiles(root, current = root, files = []) {
  if (!fs.existsSync(current)) return files;

  for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
    if (IGNORE_DIRS.has(entry.name)) continue;

    const fullPath = path.join(current, entry.name);
    if (entry.isDirectory()) {
      walkFiles(root, fullPath, files);
    } else if (entry.isFile()) {
      const ext = path.extname(entry.name).toLowerCase();
      if (CODE_EXTS.has(ext) || DOC_EXTS.has(ext)) {
        files.push(fullPath);
      }
    }
  }

  return files;
}

function makeId(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 90) || 'node';
}

function addNode(nodes, node) {
  if (!nodes.has(node.id)) {
    nodes.set(node.id, node);
  }
}

function addEdge(edges, source, target, relation, sourceFile, confidence = 'EXTRACTED', score = 1) {
  if (!source || !target || source === target) return;
  const id = `${source}->${target}:${relation}`;
  if (!edges.has(id)) {
    edges.set(id, {
      source,
      target,
      relation,
      confidence,
      confidence_score: score,
      source_file: sourceFile,
      source_location: null,
      weight: score
    });
  }
}

function extractCodeSymbols(content, relPath, nodes, edges) {
  const fileNode = `file_${makeId(relPath)}`;
  addNode(nodes, {
    id: fileNode,
    label: relPath,
    file_type: 'code',
    source_file: relPath,
    source_location: null,
    degree_hint: 0
  });

  const symbolPatterns = [
    /\bfunction\s+([A-Za-z_$][\w$]*)\s*\(/g,
    /\bclass\s+([A-Za-z_$][\w$]*)\b/g,
    /\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?\(?[^=]*?\)?\s*=>/g,
    /\bdef\s+([A-Za-z_][\w]*)\s*\(/g
  ];

  const symbols = [];
  for (const pattern of symbolPatterns) {
    let match;
    while ((match = pattern.exec(content)) !== null) {
      symbols.push(match[1]);
    }
  }

  for (const symbol of symbols.slice(0, 80)) {
    const symbolNode = `symbol_${makeId(`${relPath}_${symbol}`)}`;
    addNode(nodes, {
      id: symbolNode,
      label: symbol,
      file_type: 'code',
      source_file: relPath,
      source_location: null,
      degree_hint: 0
    });
    addEdge(edges, fileNode, symbolNode, 'defines', relPath);
  }

  const importPatterns = [
    /import\s+.*?\s+from\s+['"]([^'"]+)['"]/g,
    /require\(['"]([^'"]+)['"]\)/g,
    /^\s*from\s+([A-Za-z0-9_.]+)\s+import\s+/gm,
    /^\s*import\s+([A-Za-z0-9_.]+)/gm
  ];

  for (const pattern of importPatterns) {
    let match;
    while ((match = pattern.exec(content)) !== null) {
      const dep = match[1];
      if (!dep || dep.startsWith('node:')) continue;
      const depNode = `dep_${makeId(dep)}`;
      addNode(nodes, {
        id: depNode,
        label: dep,
        file_type: 'code',
        source_file: relPath,
        source_location: null,
        degree_hint: 0
      });
      addEdge(edges, fileNode, depNode, 'references', relPath);
    }
  }

  return { fileNode, symbols };
}

function extractDocConcepts(content, relPath, nodes, edges) {
  const fileNode = `file_${makeId(relPath)}`;
  addNode(nodes, {
    id: fileNode,
    label: relPath,
    file_type: 'document',
    source_file: relPath,
    source_location: null,
    degree_hint: 0
  });

  const headings = [...content.matchAll(/^#{1,4}\s+(.+)$/gm)].map((m) => m[1].trim()).slice(0, 40);
  for (const heading of headings) {
    const conceptNode = `concept_${makeId(`${relPath}_${heading}`)}`;
    addNode(nodes, {
      id: conceptNode,
      label: heading,
      file_type: 'rationale',
      source_file: relPath,
      source_location: null,
      degree_hint: 0
    });
    addEdge(edges, fileNode, conceptNode, 'rationale_for', relPath, 'INFERRED', 0.72);
  }
}

function topDegree(nodes, edges, count = 8) {
  const degree = {};
  for (const node of nodes.values()) degree[node.id] = 0;
  for (const edge of edges.values()) {
    degree[edge.source] = (degree[edge.source] || 0) + 1;
    degree[edge.target] = (degree[edge.target] || 0) + 1;
  }

  return [...nodes.values()]
    .map((node) => ({ ...node, degree: degree[node.id] || 0 }))
    .sort((a, b) => b.degree - a.degree)
    .slice(0, count);
}

function makeReport({ root, files, nodes, edges, godNodes }) {
  const codeCount = files.filter((file) => CODE_EXTS.has(path.extname(file).toLowerCase())).length;
  const docCount = files.length - codeCount;

  return `# GRAPH_REPORT

Generated by VibeCheck's built-in Graphify-compatible repo mapper.

## Corpus
- Workspace: ${root}
- Files analyzed: ${files.length}
- Code files: ${codeCount}
- Documentation/config files: ${docCount}
- Nodes: ${nodes.length}
- Edges: ${edges.length}

## God Nodes
${godNodes.map((node, index) => `${index + 1}. **${node.label}** (${node.source_file}) - degree ${node.degree}`).join('\n') || 'No central nodes found.'}

## Surprising Connections
${edges.filter((edge) => edge.confidence === 'INFERRED').slice(0, 8).map((edge) => `- ${edge.source} -> ${edge.target} through ${edge.relation}`).join('\n') || '- No inferred cross-file connections detected yet.'}

## Suggested Questions
- Which file or symbol is most central to the failing pipeline stage?
- Are multiple errors caused by one shared dependency or utility?
- Which files should be inspected before accepting the AI patch?
- Does the patch touch a high-degree node that deserves extra review?
`;
}

function makeHtml(graph) {
  const safeJson = JSON.stringify(graph).replace(/</g, '\\u003c');
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>VibeCheck Knowledge Graph</title>
  <style>
    body { margin: 0; font-family: Inter, system-ui, sans-serif; background: #09090b; color: #fafafa; }
    header { padding: 18px 22px; border-bottom: 1px solid #27272a; }
    main { display: grid; grid-template-columns: 320px 1fr; height: calc(100vh - 74px); }
    aside { border-right: 1px solid #27272a; padding: 18px; overflow: auto; }
    svg { width: 100%; height: 100%; background: radial-gradient(circle at 50% 30%, #18181b, #09090b); }
    .node { fill: #22c55e; stroke: #ecfeff; stroke-width: 1; }
    .edge { stroke: #52525b; stroke-opacity: 0.65; }
    text { fill: #e4e4e7; font-size: 10px; }
    li { margin: 8px 0; color: #d4d4d8; }
  </style>
</head>
<body>
  <header>
    <strong>VibeCheck Knowledge Graph</strong>
    <span style="color:#a1a1aa;margin-left:10px">${graph.nodes.length} nodes / ${graph.links.length} edges</span>
  </header>
  <main>
    <aside>
      <h3>Central Nodes</h3>
      <ol>${graph.godNodes.map((node) => `<li>${escapeHtml(node.label)} <small>${escapeHtml(node.source_file || '')}</small></li>`).join('')}</ol>
    </aside>
    <svg id="graph" viewBox="0 0 900 620"></svg>
  </main>
  <script>
    const graph = ${safeJson};
    const svg = document.getElementById('graph');
    const cx = 450, cy = 310, radius = 240;
    const nodes = graph.nodes.slice(0, 90).map((node, index, arr) => ({
      ...node,
      x: cx + Math.cos((Math.PI * 2 * index) / Math.max(arr.length, 1)) * radius,
      y: cy + Math.sin((Math.PI * 2 * index) / Math.max(arr.length, 1)) * radius
    }));
    const byId = Object.fromEntries(nodes.map((node) => [node.id, node]));
    for (const edge of graph.links.slice(0, 160)) {
      const s = byId[edge.source], t = byId[edge.target];
      if (!s || !t) continue;
      const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
      line.setAttribute('x1', s.x); line.setAttribute('y1', s.y);
      line.setAttribute('x2', t.x); line.setAttribute('y2', t.y);
      line.setAttribute('class', 'edge');
      svg.appendChild(line);
    }
    for (const node of nodes) {
      const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
      circle.setAttribute('cx', node.x); circle.setAttribute('cy', node.y);
      circle.setAttribute('r', node.file_type === 'code' ? 7 : 5);
      circle.setAttribute('class', 'node');
      svg.appendChild(circle);
      const label = document.createElementNS('http://www.w3.org/2000/svg', 'text');
      label.setAttribute('x', node.x + 9); label.setAttribute('y', node.y + 3);
      label.textContent = node.label.slice(0, 34);
      svg.appendChild(label);
    }
  </script>
</body>
</html>`;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildKnowledgeGraph(workspacePath) {
  const root = path.resolve(workspacePath);
  const outDir = path.join(root, 'graphify-out');
  fs.mkdirSync(outDir, { recursive: true });

  const files = walkFiles(root).filter((file) => {
    try {
      return fs.statSync(file).size <= 512 * 1024;
    } catch (_) {
      return false;
    }
  });

  const nodes = new Map();
  const edges = new Map();

  for (const file of files) {
    const relPath = safeRelative(root, file);
    const ext = path.extname(file).toLowerCase();
    let content = '';
    try {
      content = fs.readFileSync(file, 'utf-8');
    } catch (_) {
      continue;
    }

    if (CODE_EXTS.has(ext)) {
      extractCodeSymbols(content, relPath, nodes, edges);
    } else {
      extractDocConcepts(content, relPath, nodes, edges);
    }
  }

  const nodeList = [...nodes.values()];
  const edgeList = [...edges.values()];
  const godNodes = topDegree(nodes, edges);
  const graph = {
    directed: true,
    multigraph: false,
    graph: {
      generated_at: new Date().toISOString(),
      generator: 'vibecheck-built-in-graphify-compatible'
    },
    nodes: nodeList,
    links: edgeList,
    godNodes,
    stats: {
      files: files.length,
      nodes: nodeList.length,
      edges: edgeList.length
    }
  };

  fs.writeFileSync(path.join(outDir, 'graph.json'), JSON.stringify(graph, null, 2), 'utf-8');
  fs.writeFileSync(path.join(outDir, 'GRAPH_REPORT.md'), makeReport({ root, files, nodes: nodeList, edges: edgeList, godNodes }), 'utf-8');
  fs.writeFileSync(path.join(outDir, 'graph.html'), makeHtml(graph), 'utf-8');

  return {
    outputDir: outDir,
    graphPath: path.join(outDir, 'graph.json'),
    reportPath: path.join(outDir, 'GRAPH_REPORT.md'),
    htmlPath: path.join(outDir, 'graph.html'),
    stats: graph.stats,
    godNodes
  };
}

function readKnowledgeContext(workspacePath, limit = 12000) {
  const outDir = path.join(workspacePath, 'graphify-out');
  const reportPath = path.join(outDir, 'GRAPH_REPORT.md');
  const graphPath = path.join(outDir, 'graph.json');

  if (!fs.existsSync(reportPath) || !fs.existsSync(graphPath)) {
    return '';
  }

  const report = fs.readFileSync(reportPath, 'utf-8');
  let summary = report;

  try {
    const graph = JSON.parse(fs.readFileSync(graphPath, 'utf-8'));
    const central = (graph.godNodes || [])
      .slice(0, 12)
      .map((node) => `- ${node.label} (${node.source_file}, degree ${node.degree})`)
      .join('\n');
    summary += `\n\n## Machine Summary\nFiles: ${graph.stats?.files || 0}; Nodes: ${graph.stats?.nodes || 0}; Edges: ${graph.stats?.edges || 0}\nCentral nodes:\n${central}`;
  } catch (_) {}

  return summary.slice(0, limit);
}

module.exports = {
  buildKnowledgeGraph,
  readKnowledgeContext
};
